version: "3"
services:
  nginx:
    build: ./requirements/nginx
    ports:
     - "8080:80"
    tty: true
    networks:
     - incep
    volumes:
     - data:/var/www/html
     - ./requirements/nginx/default:/etc/nginx/sites-available/default

  wordpress:
    build: ./requirements/wordpress/
    tty: true
    networks:
     - incep
    volumes:
    - data:/var/www/html
    - ./requirements/wordpress/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
volumes:
    data:

networks:
   incep:
