version: "3"
services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    restart: always
    ports:
     - "80:80"
     - "443:443"
    networks:
     - webservenet
    volumes:
     - data:/var/www/html
     - ./requirements/nginx/default:/etc/nginx/sites-available/default
    depends_on:
     - wordpress


  wordpress:
    image: wordpress
    build: ./requirements/wordpress/
    restart: always
    networks:
     - dbnet
     - webservenet
    volumes:
     - data:/var/www/html
     - ./requirements/wordpress/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
    env_file:
     - ./.env
    depends_on:
      mariadb:
        condition: service_healthy


  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    restart: always
    networks:
     - dbnet
    env_file:
     - ./.env
    volumes:
     - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=user --password=password -e 'SELECT 1'"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 3s

volumes:
    data:
    mariadb_data:

networks:
   webservenet:
   dbnet:
