version: "3"
services:
  nginx:
    build: ./requirements/nginx
    restart: always
    ports:
     - "8080:80"
    networks:
     - webservenet
    volumes:
     - data:/var/www/html
     - ./requirements/nginx/default:/etc/nginx/sites-available/default
    depends_on:
     - wordpress


  wordpress:
    build: ./requirements/wordpress/
    restart: always
    networks:
     - dbnet
     - webservenet
    volumes:
    - data:/var/www/html
    - ./requirements/wordpress/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
    env_file:
    - ./requirements/wordpress/wordpress-variables.env


  mariadb:
    build: ./requirements/mariadb/
    restart: always
    networks:
     - dbnet
    env_file:
    - ./requirements/mariadb/mariadb-variables.env
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
    data:
    mariadb_data:

networks:
   webservenet:
   dbnet:
