version: "3"
services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    restart: always
    ports:
    #  - "80:80"
     - "443:443"
    networks:
     - webservenet
    volumes:
     - wordpress:/var/www/html
     - ./requirements/nginx/default:/etc/nginx/sites-available/default
    depends_on:
     - wordpress


  wordpress:
    image: wordpress
    build: ./requirements/wordpress/
    restart: always
    networks:
     - dbnet
     - webservenet
    volumes:
     - wordpress:/var/www/html
     - ./requirements/wordpress/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
    env_file:
     - ./.env
    depends_on:
      mariadb:
        condition: service_healthy


  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    restart: always
    networks:
     - dbnet
    env_file:
     - ./.env
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -uuser -ppassword -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 60s

volumes:
    db:
      name: db
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /home/rnaka/data/mysql
    wordpress:
      name: wordpress
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /home/rnaka/data/wordpress

networks:
   webservenet:
   dbnet: