FROM debian:bullseye

RUN	apt-get update \
	&& apt-get install -y vim nginx openssl \
	&& mkdir -p /etc/nginx/ssl
#	&& openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt


CMD	["nginx", "-g", "daemon off;"]
